[package]
name = "bevy_flow"
version = "1.14.0"
edition = "2021"


[dependencies]
async-channel = "2.3"


[dependencies.bevy]
version = "0.14"
default-features = false
features = [
    "bevy_asset",
    "bevy_state"
]
