[package]
name = "bevy_flow"
version = "1.0.0"
edition = "2021"


[dependencies]
async-channel = "2.3"


[dependencies.bevy]
version = "0.13.2"
# default-features = false
# features = [ "bevy_asset" ]
